name: Docker Security

on:
  push:
    branches: [main]
  schedule:
    - cron: "29 5 * * 1"
  workflow_dispatch: {}

permissions: {}

jobs:
  scan:
    permissions:
      contents: read
      security-events: write # upload hadolint and Trivy results
    uses: rknightion/.github/.github/workflows/docker-security.yml@81fc55183265da0b21e92e690f70d679b20ed822 # v1.21.0
