name: Docker Security

on:
  push:
    branches: [main]
  schedule:
    - cron: "29 5 * * 1"
  workflow_dispatch: {}

permissions: {}

jobs:
  scan:
    permissions:
      contents: read
      security-events: write # upload hadolint and Trivy results
    uses: rknightion/.github/.github/workflows/docker-security.yml@1ee56349bfcf2568e538479918b9bdd1b9196309 # v1.15.1
