name: zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read
      security-events: write # upload zizmor results
      actions: read          # inspect workflow metadata
    uses: rknightion/.github/.github/workflows/zizmor.yml@c36bf7ded21407b0a5169ecb2502d6a3a385be30 # v1.25.5
