name: zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read
      security-events: write # upload zizmor results
      actions: read          # inspect workflow metadata
    uses: rknightion/.github/.github/workflows/zizmor.yml@c636bd20758433033cb4fe7760867b1318523bbb # v1.17.0
