name: zizmor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  zizmor:
    permissions:
      contents: read
      security-events: write # upload zizmor results
      actions: read          # inspect workflow metadata
    uses: rknightion/.github/.github/workflows/zizmor.yml@4d749e93fb2ba8ae3d213c21686bc7ac204bb928 # v1.23.0
